version: '3'
services:
  spark-master:
    image: reddys310/spark-master:latest
    container_name: spark-master
    volumes:
      - "./notebooks/data:/data"
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "PYSPARK_DRIVER_PYTHON=ipython"
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  spark-worker-1:
    image: reddys310/spark-worker:latest
    container_name: spark-worker-1
    volumes:
      - "./notebooks/data:/data"
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "PYSPARK_DRIVER_PYTHON=ipython"
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  spark-worker-2:
    image: reddys310/spark-worker:latest
    container_name: spark-worker-2
    volumes:
      - "./notebooks/data:/data"
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "PYSPARK_DRIVER_PYTHON=ipython"
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  spark-worker-3:
    image: reddys310/spark-worker:latest
    container_name: spark-worker-3
    volumes:
      - "./notebooks/data:/data"
    depends_on:
      - spark-master
    ports:
      - "8083:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "PYSPARK_DRIVER_PYTHON=ipython"
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  jupyter-notebook:
    image: jupyter/all-spark-notebook:latest
    container_name: jupyter-notebook
    volumes:
      - "./notebooks:/home/jovyan/work/notebooks"
    depends_on:
      - spark-master
    ports:
      - "8888:8888"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
